name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Set up MySQL service
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 123456789 # Set root password
          MYSQL_DATABASE: momin # Optional: Initialize a database
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Navigate to the correct directory
      - name: Change directory to Java project
        working-directory: "./Assignment 2" # Path to Assignment 2 folder (fix path)
        run: pwd

      # Step 4: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 5: Install dependencies and build the project
      - name: Build with Maven
        working-directory: "./Assignment 2" # Path to Assignment 2 folder (fix path)
        run: mvn clean install

      # Step 6: Run unit tests
      - name: Run Tests
        working-directory: "./Assignment 2" # Path to Assignment 2 folder (fix path)
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: 123456789
        run: mvn test
